import {test,expect} from '@playwright/test';
import {mkdirSync} from 'node:fs';
const pages=['','about/','products/','services/','projects/','contact/','privacy/','products/rotary-evaporator/','products/laboratory-support/','products/glass-condenser/','projects/distillation-apparatus/','projects/education-glassware/'];
test('all demo routes load in both languages and maintain their counterpart',async({page})=>{
 for(const lang of ['en','id'])for(const route of pages){await page.goto(`/${lang}/${route}`);await expect(page.locator('h1')).toBeVisible();await expect(page.locator('html')).toHaveAttribute('lang',lang);await expect(page.locator('.languages a').filter({hasText:lang==='en'?'Indonesia':'English'})).toHaveAttribute('href',`/${lang==='en'?'id':'en'}/${route}`);await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content','noindex,nofollow');await page.locator('img').evaluateAll(imgs=>imgs.forEach(img=>(img as HTMLImageElement).loading='eager'));await expect.poll(async()=>page.locator('img').evaluateAll(imgs=>imgs.filter(img=>!(img as HTMLImageElement).complete||!(img as HTMLImageElement).naturalWidth).length)).toBe(0);const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(img=>!(img as HTMLImageElement).complete||!(img as HTMLImageElement).naturalWidth).length);expect(broken).toBe(0);}
 await page.goto('/');await expect(page).toHaveURL(/\/en\/$/);
});
test('catalogue search, empty results and category filter work',async({page})=>{await page.goto('/en/products/');await page.locator('#search').fill('condenser');await expect(page.locator('[data-product]:visible')).toHaveCount(1);await page.locator('#search').fill('nonexistent');await expect(page.locator('#empty-results')).toBeVisible();await page.locator('#search').fill('');await page.locator('#category').selectOption('rotary');await expect(page.locator('[data-product]:visible')).toHaveCount(1);});
test('enquiry is validated and opens WhatsApp with correct office and product context',async({page})=>{await page.goto('/id/contact/?product=Kondensor%20Kaca');await expect(page.locator('#enquiry-product')).toHaveValue('Kondensor Kaca');await page.locator('#enquiry-form button').click();await expect(page).toHaveURL(/\/id\/contact/);await page.locator('#enquiry-name').fill('Demo Client');await page.locator('#enquiry-message').fill('Butuh kondensor custom');let destination='';await page.route('https://wa.me/**',async route=>{destination=route.request().url();await route.fulfill({body:'WhatsApp handoff'});});await page.locator('#enquiry-form button').click();await expect.poll(()=>destination).toContain('wa.me/628112341010');expect(decodeURIComponent(destination)).toContain('Kondensor Kaca');});
test('mobile menu, language change and responsive layouts',async({page})=>{mkdirSync('documentation/docs/demo',{recursive:true});for(const width of [320,390,768,1440]){await page.setViewportSize({width,height:900});for(const lang of ['en','id']){await page.goto(`/${lang}/`);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);if(width===390){await page.locator('.menu-toggle').click();await expect(page.locator('#navigation')).toBeVisible();await page.keyboard.press('Escape');await expect(page.locator('.menu-toggle')).toHaveAttribute('aria-expanded','false');}await page.locator('img').evaluateAll(imgs=>imgs.forEach(img=>(img as HTMLImageElement).loading='eager'));await expect.poll(async()=>page.locator('img').evaluateAll(imgs=>imgs.filter(img=>!(img as HTMLImageElement).complete||!(img as HTMLImageElement).naturalWidth).length)).toBe(0);expect(await page.locator('.product-image img').evaluateAll(imgs=>imgs.every(img=>{const a=img.getBoundingClientRect(),b=img.parentElement!.getBoundingClientRect();return a.bottom<=b.bottom+1&&a.top>=b.top-1;}))).toBe(true);if(width===390||width===1440)await page.screenshot({path:`documentation/docs/demo/home-${lang}-${width}.png`,fullPage:true});}await page.goto('/en/contact/');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);}});
